---
- name: Install ypserv using group variables
  hosts: linux
  become: true
  tasks:
    - name: Debug packages variable
      debug:
        var: packages

    - name: Install ypserv package
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

