---
- name: Ensure /etc/profile is updated
  lineinfile:
    path: /etc/profile
    line: "{{ item }}"
    state: present
  with_items:
    - "#Test block added by Ansible……{{ username }}"
    - "export TMOUT={{ timeout }}"
  become: true
