---
- name: Create an empty file called locfile on the automation machine
  local_action:
    module: file
    path: "{{ locfile_path }}"
    state: touch

- name: Copy locfile to the managed nodes under the /tmp directory
  copy:
    src: "{{ locfile_path }}"
    dest: "{{ locfile_dest }}"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    mode: "{{ file_mode }}"

- name: Display the status of the /tmp/locfile file
  command: ls -l /tmp/locfile
  register: locfile_status

- name: Show the status of the /tmp/locfile file
  debug:
    msg: "{{ locfile_status.stdout }}"

- name: Create an empty file called emptyfile on the managed nodes
  file:
    path: "{{ emptyfile_path }}"
    state: touch
