---
- name: Add string to file based on OS and kernel versions
  hosts: linux
  become: true
  tasks:
    - name: Gather OS facts
      ansible.builtin.setup:
        gather_subset:
          - "hardware"
          - "network"
          - "virtual"
          - "!all"

    - name: Add string to file if conditions are met
      ansible.builtin.blockinfile:
        path: /tmp/conditional
        block: |
          This is my CentOS VM
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "8"
        - ansible_distribution_version == "8.2"
        - ansible_kernel == "4.18.0-193.el8.x86_64"
